name: poultry_management_app
description: A Flutter app for managing poultry information

publish_to: 'none' # Remove this line if you want to publish to the app store.

environment:
  sdk: ">=2.12.0 <4.0.0"  # Updated to support Dart SDK 2.12.0 and above.

dependencies:
  flutter:
    sdk: flutter

  # Other dependencies can be added here.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
